name: Check homework

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: demo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: echo "PROJECTPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Load demo data
        run: |
          export PGPASSWORD="$POSTGRES_PASSWORD"
          psql --host=localhost \
               --port=5432 \
               --username="$POSTGRES_USER" \
               --dbname="$POSTGRES_DB" \
               < "$PROJECTPATH/tests/data/demo.sql"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
