name: Check homework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set project path
        run: echo "PROJECTPATH=/home/runner/work/backend_test_homework3/backend_test_homework3" >> $GITHUB_ENV

      - name: Load demo data
        run: |
          export PGPASSWORD="$POSTGRES_PASSWORD"
          psql --host="$POSTGRES_HOST" \
               --port="$POSTGRES_PORT" \
               --username="$POSTGRES_USER" \
               --dbname="$POSTGRES_DB" \
               < "$PROJECTPATH/tests/data/demo.sql"

      - name: Run tests
        run: pytest -v
